version: '3.8'

services:
  redis-node1:
    image: redis:7.0-alpine
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - redis-node1-data:/data
    networks:
      - redis-cluster
    deploy:
      replicas: 1

  redis-node2:
    image: redis:7.0-alpine
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - redis-node2-data:/data
    networks:
      - redis-cluster
    deploy:
      replicas: 1

  redis-node3:
    image: redis:7.0-alpine
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - redis-node3-data:/data
    networks:
      - redis-cluster
    deploy:
      replicas: 1

  redis-node4:
    image: redis:7.0-alpine
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - redis-node4-data:/data
    networks:
      - redis-cluster
    deploy:
      replicas: 1

  redis-node5:
    image: redis:7.0-alpine
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - redis-node5-data:/data
    networks:
      - redis-cluster
    deploy:
      replicas: 1

  redis-node6:
    image: redis:7.0-alpine
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - redis-node6-data:/data
    networks:
      - redis-cluster
    deploy:
      replicas: 1

networks:
  redis-cluster:
    driver: overlay

volumes:
  redis-node1-data:
  redis-node2-data:
  redis-node3-data:
  redis-node4-data:
  redis-node5-data:
  redis-node6-data:
