version: '3.8'

networks:
  testing_network:

volumes:
  influxdb_data:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - testing_network
    environment:
      - INFLUXDB_DB=k6
      - K6_INFLUXDB_PAYLOAD_SIZE=1MB 
    volumes:
      - influxdb_data:/var/lib/influxdb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "2"
          memory: 1G

  grafana:
    image: grafana/grafana:latest
    networks:
      - testing_network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin     # Set your custom username
      - GF_SECURITY_ADMIN_PASSWORD=1234 # Set your custom password
      - GF_AUTH_ANONYMOUS_ORG_ROLE=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DATASOURCE_URL=http://influxdb:8086
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  fastapi:
    image: python:3.12.6-alpine
    networks:
      - testing_network
    volumes:
      - ./fastapi:/app
    command: sh -c "cd /app && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --workers=1"
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:8000/ping || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    deploy:
      replicas: 1
      update_config:
        parallelism: 5
        delay: 5s
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: "2"
      #     memory: 3G

  k6:
    image: grafana/k6:latest
    networks:
      - testing_network
    # ports:
    #   - "5665:5665"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      # - K6_WEB_DASHBOARD=true
    volumes:
      - ./k6:/scripts
    command: run /scripts/run_docker.js
    depends_on:
      - fastapi
      - influxdb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        # max_attempts: 20
      resources:
        limits:
          cpus: "2"
          memory: 1G

