apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Prometheus service URL in the Docker network
    isDefault: true  # Set Prometheus as the default data source
    version: 1
    editable: true
    id: prometheus  # Unique ID for Prometheus

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      tlsSkipVerify: false
      tlsAuth: false
    # secureJsonData:
    #   password: your_redis_password