version: '3.8'

services:
  redis:
    image: redis:latest
    # ports:
    #   - "6379:6379"
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data
    networks:
      - monitoring

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    restart: unless-stopped
    networks:
      - monitoring
    deploy:
      replicas: 1

volumes:
  redis-data:
  redisinsight-data:

networks:
  monitoring:
    driver: overlay