{
 "title": "k6 Load Testing Results Simple filters",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the InfluxDB exporter. It supports http, ws, grpc, ... metrics",
 "time": { "from": "2024-08-28T15:16:48.689Z", "to": "2024-08-28T15:30:00.761Z" },
 "templating": {
  "list": [
   { "name": "source", "query": "influxdb" },
   { "name": "Measurement", "query": "SHOW MEASUREMENTS" },
   {
    "name": "scenario",
    "query": "SELECT \"scenario\"\nFROM\n(SELECT last(\"value\")\n FROM \"${Measurement}\"\n GROUP BY \"scenario\")\nWHERE  $timeFilter"
   },
   { "name": "URL", "label": "URL", "query": ".+" },
   {
    "name": "name",
    "query": "SELECT \"name\"\nFROM\n(SELECT last(\"value\")\n FROM \"${Measurement}\"\n WHERE \"name\" =~ /^${URL:raw}$/ AND \"scenario\" =~ /^${scenario:regex}$/\n GROUP BY \"name\")\nWHERE $timeFilter"
   },
   { "name": "T", "query": "50" }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "### To choose which measurements to show, use the **Measurements** drop-down in the top left corner!\n\nK6 collects metrics for several phases during the HTTP request lifetime.\n\nThe combined delays for the application and network (send, wait, recieve) are available in this metric:\n  * **http_req_duration**       _( Total time for request, excluding time spent blocked (http_req_blocked), DNS lookup (http_req_looking_up) and TCP connect (http_req_connecting) time. )_\n\nThis metric can also be broken down into these metrics:\n  * **http_req_tls_handshaking**     _( Time spent handshaking TLS session with remote host. )_\n  * **http_req_sending**      _( Time spent sending data to remote host.  )_\n  * **http_req_waiting**      _( Time spent waiting for response from remote host (a.k.a. \"time to first byte\", or \"TTFB\"). )_\n  * **http_req_receiving**       _( Time spent receiving response data from remote host. )_\n\nThese metrics measure delays and durations on the client:\n\n  * **http_req_blocked**     _( Time spent blocked (waiting for a free TCP connection slot) before initiating request.  )_\n  * **http_req_looking_up**     _( Time spent looking up remote host name in DNS. )_\n  * **http_req_connecting**     _( Time spent establishing TCP connection to remote host. )_\n\n\n### View official K6.io documentation here: [https://docs.k6.io/docs/result-metrics][1]\n\n\n[1]: https://docs.k6.io/docs/result-metrics\n\n"
     }
    }
   ]
  },
  { "title": "$Measurement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "Measurement" },
  {
   "title": "$Measurement (over time)",
   "type": "timeseries",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" },
       { "params": [ "rps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "90%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "85" ], "type": "percentile" },
       { "params": [ "85%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "80" ], "type": "percentile" },
       { "params": [ "80%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" },
       { "params": [ "75%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "50%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "25" ], "type": "percentile" },
       { "params": [ "25%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (count)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "URLs and latencies",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT count(\"value\"), min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95) FROM /^$Measurement$/ WHERE (\"name\" =~ /^${URL:raw}$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY \"name\", \"scenario\", \"group\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "p95" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "sCount",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"value\") as \"sCount\"  FROM /^${Measurement:regex}$/ WHERE ( \"name\" =~ /^${URL:raw}$/ AND \"scenario\" =~ /^${scenario:regex}$/ AND \"value\" <= ${T:raw}) AND $timeFilter GROUP BY \"name\", \"scenario\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "sTime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "${T:raw}" }
     ]
    },
    {
     "alias": "tCount",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT count(\"value\")/2.0 as \"tCount\"  FROM /^${Measurement:regex}$/ WHERE ( \"name\" =~ /^${URL:raw}$/ AND \"scenario\" =~ /^$scenario$/ AND \"value\" > ${T:raw} AND \"value\" <= 4*${T:raw}) AND $timeFilter GROUP BY \"name\", \"scenario\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "sTime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "value", "operator": "<", "value": "${T:raw}" }
     ]
    }
   ]
  },
  { "title": "K6 Test overview (all URLs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Virtual Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_scenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "*1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Network (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "$tag_scenario - received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_received",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "$tag_scenario - sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_sent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "alias": "$tag_scenario",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  { "title": "${Measurement} for scenario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "$scenario",
   "type": "timeseries",
   "description": "Grouped by 1 sec intervals",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "repeat": "scenario",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "rps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " * 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT max(\"value\") AS \"max\", percentile(\"value\", 99) AS \"99%\", percentile(\"value\", 95) AS \"95%\", percentile(\"value\", 90) AS \"90%\", percentile(\"value\", 85) AS \"85%\", percentile(\"value\", 80) AS \"80%\", percentile(\"value\", 75) AS \"75%\", percentile(\"value\", 50) AS \"50%\", percentile(\"value\", 25) AS \"25%\", min(\"value\") AS \"min\" FROM /^${Measurement:regex}$/ WHERE (\"name\" =~ /^${URL:raw}$/ AND \"scenario\" =~ /^$scenario$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "90%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "85" ], "type": "percentile" },
       { "params": [ "85%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "80" ], "type": "percentile" },
       { "params": [ "80%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" },
       { "params": [ "75%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "50%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "25" ], "type": "percentile" },
       { "params": [ "25%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  {
   "title": "$scenario",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "repeat": "scenario",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
     ]
    }
   ]
  },
  { "title": "${Measurement} for Name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "$name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "repeat": "name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "rps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "* 1000 / $__interval_ms" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "max" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "99" ], "type": "percentile" },
       { "params": [ "99%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" },
       { "params": [ "95%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" },
       { "params": [ "90%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "85" ], "type": "percentile" },
       { "params": [ "85%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "80" ], "type": "percentile" },
       { "params": [ "80%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "75" ], "type": "percentile" },
       { "params": [ "75%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "50" ], "type": "percentile" },
       { "params": [ "50%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "25" ], "type": "percentile" },
       { "params": [ "25%" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "$name",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "repeat": "name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^$Measurement$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$name$/" }
     ]
    }
   ]
  },
  {
   "title": "Custom HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP only - avg (over time)",
     "type": "graph",
     "description": "Grouped by 1 sec intervals",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "duration",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      },
      {
       "alias": "waiting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_waiting",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      },
      {
       "alias": "blocked",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_blocked",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      },
      {
       "alias": "connecting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_connecting",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      },
      {
       "alias": "receiving",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_receiving",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      },
      {
       "alias": "sending",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_sending",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      },
      {
       "alias": "tls handshaking",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_tls_handshaking",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^${URL:raw}$/" },
        { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenario$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}